CREATE TABLE [dbo].[Comments]
(
	[CommentID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[UserID] UNIQUEIDENTIFIER NOT NULL,
	[RecipeID] UNIQUEIDENTIFIER,
	[ArticleID] UNIQUEIDENTIFIER,
	CommentText varchar(max) not null,
	CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2 DEFAULT GETDATE()
)
