CREATE TABLE [dbo].[RecipeCategories]
(
	[RecipeCategoryID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[RecipeID] UNIQUEIDENTIFIER NOT NULL,
	[CategoryID] UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2 DEFAULT GETDATE()
)
